name: Deploy to Dev Remote Server

on:
  push:
    branches:
      - dev
  workflow_dispatch:

# These permissions are required for the OIDC token exchange with AWS.
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest

    env:
      LOCAL_PATH: build
      REMOTE_USER: ubuntu
      REMOTE_PATH: /home/ubuntu/mmhc-backend-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Npm Run Build
        run: |
          npm run build

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          # The ARN of the IAM role to assume.
          # This role MUST be configured in your AWS account to trust the GitHub OIDC provider.
          # Store this as a secret in GitHub repository settings: Settings > Secrets and variables > Actions > New repository secret
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_GITHUB }}

          # The AWS region where your resources are located.
          # Store this as a variable in GitHub repository settings: Settings > Secrets and variables > Actions > New repository variable
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy files to EC2 via Rsync and SSM
        run: |
          echo "Starting deployment to EC2 instance ${{ secrets.EC2_INSTANCE_ID }}"...



          rsync -avz --delete \
            -e 'ssh -o StrictHostKeyChecking=no -o ProxyCommand="aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p"' \
            ${{ env.LOCAL_PATH }} \
            ${{ env.REMOTE_USER }}@${{ secrets.EC2_INSTANCE_ID }}:${{ env.REMOTE_PATH }}

          echo "Deployment successful."
