name: Deploy to Dev Remote Server

on:
  push:
    branches:
      - dev
  workflow_dispatch:

# These permissions are required for the OIDC token exchange with AWS.
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Application to EC2
    runs-on: ubuntu-latest

    env:
      LOCAL_PATH: build
      REMOTE_PATH: /home/ubuntu/mmhc-backend-dev
      AVAILABILITY_ZONE: us-east-1f

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Npm Run Build
        run: |
          npm run build

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          # The ARN of the IAM role to assume.
          # This role MUST be configured in your AWS account to trust the GitHub OIDC provider.
          # Store this as a secret in GitHub repository settings: Settings > Secrets and variables > Actions > New repository secret
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_GITHUB }}

          # The AWS region where your resources are located.
          # Store this as a variable in GitHub repository settings: Settings > Secrets and variables > Actions > New repository variable
          aws-region: ${{ secrets.AWS_REGION }}

      # ---------- Generate SSH key for temporary login ----------
      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -N "" -f temp_key
          echo "Key generated"

      # ---------- Push public key using EC2 Instance Connect ----------
      - name: Send SSH Key to EC2
        run: |
          aws ec2-instance-connect send-ssh-public-key \
            --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
            --instance-os-user ubuntu \
            --availability-zone ${{ env.AVAILABILITY_ZONE }} \
            --ssh-public-key file://temp_key.pub

      - name: Rsync to EC2
        run: |
          rsync -avzrtu --delete --progress --exclude="node_modules" --exclude="tmp" \
            -e "ssh -i temp_key -o StrictHostKeyChecking=no" \
            ./build/ \
            ubuntu@${{ secrets.EC2_PUBLIC_IP }}:${{ env.REMOTE_PATH }}

          echo
          echo "** Running commands on remote host named $_remote **"
          echo

          # connect to remote server
          ssh -T "$_user"@"$_remote" "bash -s $_remote_directory_name" <<'EOL'
          #!/bin/bash

          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          export HOME="/home/ubuntu/"
          #
          now="$(date)"
          name="$HOSTNAME"
          up="$(uptime)"
          echo "Server name is $name"
          echo "Server date and time is $now"
          echo "Server uptime: $up"
          echo "remote_directory_name : $1"
          _remote_directory_name=$1
          _pm2_server_ref=$1
          NODE_INTERPRETER="/home/ubuntu/.nvm/versions/node/v22.21.1/bin/node"



          echo "Deployment successful."
